name: gaussian_splatting
channels:
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - cuda-toolkit=12.8
  - plyfile
  - python=3.9
  - pip=22.3.1
  - tqdm
  - pip:
    - wandb
    - Pillow
    - opencv-python
    - --pre torch torchvision --index-url https://download.pytorch.org/whl/nightly/cu128 
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
